apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: smart-farm-web
  name: smart-farm-web
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: smart-farm-web
status:
  loadBalancer: {}
